// examples/react-example.tsx
// React kullanım örneği
import * as React from 'react';
import { Button } from '@arcadia-components/button/bindings/react';
import { HelloWorld } from '@arcadia-components/hello-world/bindings/react';

export function App() {
  const handleButtonClick = (event: CustomEvent<MouseEvent>) => {
    console.log('Button clicked!', event.detail);
    alert('Button clicked!');
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'Arial, sans-serif' }}>
      <h1>React Components Test</h1>
      
      <section style={{ marginBottom: '20px' }}>
        <h2>HelloWorld Component</h2>
        <HelloWorld />
      </section>

      <section>
        <h2>Button Component</h2>
        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
          <Button 
            variant="primary" 
            size="small"
            onButtonClick={handleButtonClick}
          >
            Primary Small
          </Button>
          
          <Button 
            variant="secondary" 
            size="medium"
            onButtonClick={handleButtonClick}
          >
            Secondary Medium
          </Button>
          
          <Button 
            variant="danger" 
            size="large"
            onButtonClick={handleButtonClick}
          >
            Danger Large
          </Button>
          
          <Button 
            variant="primary" 
            disabled={true}
            onButtonClick={handleButtonClick}
          >
            Disabled
          </Button>
        </div>
      </section>
    </div>
  );
}

export default App;

// examples/vue-example.vue
<!-- Vue kullanım örneği -->
<template>
  <div style="padding: 20px; font-family: Arial, sans-serif">
    <h1>Vue Components Test</h1>
    
    <section style="margin-bottom: 20px">
      <h2>HelloWorld Component</h2>
      <hello-world />
    </section>

    <section>
      <h2>Button Component</h2>
      <div style="display: flex; gap: 10px; flex-wrap: wrap">
        <comp-button 
          variant="primary" 
          size="small"
          @buttonClick="handleButtonClick"
        >
          Primary Small
        </comp-button>
        
        <comp-button 
          variant="secondary" 
          size="medium"
          @buttonClick="handleButtonClick"
        >
          Secondary Medium
        </comp-button>
        
        <comp-button 
          variant="danger" 
          size="large"
          @buttonClick="handleButtonClick"
        >
          Danger Large
        </comp-button>
        
        <comp-button 
          variant="primary" 
          :disabled="true"
          @buttonClick="handleButtonClick"
        >
          Disabled
        </comp-button>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
const handleButtonClick = (event: CustomEvent<MouseEvent>) => {
  console.log('Button clicked!', event.detail);
  alert('Button clicked!');
};
</script>

<style scoped>
/* Component-specific styles */
</style>
